getwd()
setwd('genero/')
library(readr)
library(tidyr)
library(dplyr)
library(forcats)
library(readxl)
library(readr)
library(stringr)
library(kableExtra)
library(ggplot2)
library(ggthemes)
library(ggrepel)
library(scales)
library(sidrar)

dados<- get_sidra(api= "/t/4093/n1/all/n2/2/n3/21/v/4088,4090,4092,4094/p/all/c2/allxt")
